apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jdsrbtki7-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jdsrbtki7-go 
  name: jdsrbtki7-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jdsrbtki7-go 
